// @generated by scripts/sklearn_conformance.py --update
// Public scikit-learn APIs only; project-owned black-box outputs.

pub const SKLEARN_VERSION: &str = "1.9.0";
pub const NUMPY_VERSION: &str = "2.4.1";
pub const EXACT_TRAIN_X: &[f32] = &[0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 1.0, 1.0, 2.0, 0.0, 2.0, 1.0, 3.0, 0.0, 3.0, 1.0];
pub const EXACT_CLASSIFIER_Y: &[u8] = &[0, 0, 0, 1, 1, 1, 1, 0];
pub const EXACT_REGRESSION_Y: &[f32] = &[-1.0, 0.0, 1.0, 2.0, 4.0, 6.0, 7.0, 9.0];
pub const EXACT_TEST_X: &[f32] = &[-1.0, 0.5, 0.5, 0.5, 1.5, 0.5, 2.5, 0.5, 4.0, 0.5];
pub const EXACT_CLASSES: &[u8] = &[0, 1];
pub const EXACT_LABELS: &[u8] = &[0, 0, 0, 1, 1];
pub const EXACT_PROBABILITIES: &[f32] = &[1.0, 0.0, 1.0, 0.0, 0.5, 0.5, 0.25, 0.75, 0.25, 0.75];
pub const EXACT_REGRESSION: &[f32] = &[-0.5, -0.5, 1.5, 5.0, 8.0];
pub const TIE_TRAIN_X: &[f32] = &[0.0, 1.0, 2.0, 3.0];
pub const TIE_Y: &[u8] = &[0, 1, 0, 1];
pub const TIE_TEST_X: &[f32] = &[-1.0, 1.5, 4.0];
pub const TIE_CLASSES: &[u8] = &[0, 1];
pub const TIE_LABELS: &[u8] = &[0, 0, 0];
pub const TIE_PROBABILITIES: &[f32] = &[0.5, 0.5, 0.5, 0.5, 0.5, 0.5];
pub const SINGLE_CLASSES: &[u8] = &[1];
pub const SINGLE_LABELS: &[u8] = &[1, 1, 1];
pub const SINGLE_PROBABILITIES: &[f32] = &[1.0, 1.0, 1.0];


#[derive(Clone, Copy, Debug)]
pub struct QualityReference {
    pub lane: &'static str,
    pub seed: u64,
    pub accuracy: f64,
    pub brier: f64,
    pub nrmse: f64,
}

pub const QUALITY_REFERENCES: &[QualityReference] = &[
    QualityReference { lane: "nonlinear", seed: 11, accuracy: 0.796875, brier: 0.1457828871414186, nrmse: 0.0 },
    QualityReference { lane: "nonlinear", seed: 22, accuracy: 0.80208333333333337, brier: 0.14932076847811335, nrmse: 0.0 },
    QualityReference { lane: "nonlinear", seed: 33, accuracy: 0.79166666666666663, brier: 0.147231028173436, nrmse: 0.0 },
    QualityReference { lane: "nonlinear", seed: 44, accuracy: 0.8203125, brier: 0.12913574370613376, nrmse: 0.0 },
    QualityReference { lane: "nonlinear", seed: 55, accuracy: 0.84635416666666663, brier: 0.12194236913114832, nrmse: 0.0 },
    QualityReference { lane: "separable", seed: 11, accuracy: 0.9375, brier: 0.064554750021343629, nrmse: 0.0 },
    QualityReference { lane: "separable", seed: 22, accuracy: 0.93489583333333337, brier: 0.075241239671523671, nrmse: 0.0 },
    QualityReference { lane: "separable", seed: 33, accuracy: 0.9296875, brier: 0.062495212514582309, nrmse: 0.0 },
    QualityReference { lane: "separable", seed: 44, accuracy: 0.93229166666666663, brier: 0.072392004836565008, nrmse: 0.0 },
    QualityReference { lane: "separable", seed: 55, accuracy: 0.921875, brier: 0.075474589798661687, nrmse: 0.0 },
    QualityReference { lane: "imbalanced", seed: 11, accuracy: 0.97395833333333337, brier: 0.021407723886718199, nrmse: 0.0 },
    QualityReference { lane: "imbalanced", seed: 22, accuracy: 0.96875, brier: 0.029041850242724789, nrmse: 0.0 },
    QualityReference { lane: "imbalanced", seed: 33, accuracy: 0.9765625, brier: 0.017646585128842388, nrmse: 0.0 },
    QualityReference { lane: "imbalanced", seed: 44, accuracy: 0.97135416666666663, brier: 0.022902062014757012, nrmse: 0.0 },
    QualityReference { lane: "imbalanced", seed: 55, accuracy: 0.98177083333333337, brier: 0.015551708653178389, nrmse: 0.0 },
    QualityReference { lane: "noise", seed: 11, accuracy: 0.47916666666666669, brier: 0.25906989287062893, nrmse: 0.0 },
    QualityReference { lane: "noise", seed: 22, accuracy: 0.51822916666666663, brier: 0.25285428698533957, nrmse: 0.0 },
    QualityReference { lane: "noise", seed: 33, accuracy: 0.48697916666666669, brier: 0.25721229280205754, nrmse: 0.0 },
    QualityReference { lane: "noise", seed: 44, accuracy: 0.54947916666666663, brier: 0.24965895039890071, nrmse: 0.0 },
    QualityReference { lane: "noise", seed: 55, accuracy: 0.53385416666666663, brier: 0.25229331787028803, nrmse: 0.0 },
    QualityReference { lane: "regression", seed: 11, accuracy: 0.0, brier: 0.0, nrmse: 0.24186311590882517 },
    QualityReference { lane: "regression", seed: 22, accuracy: 0.0, brier: 0.0, nrmse: 0.23901463672470494 },
    QualityReference { lane: "regression", seed: 33, accuracy: 0.0, brier: 0.0, nrmse: 0.26025475911554852 },
    QualityReference { lane: "regression", seed: 44, accuracy: 0.0, brier: 0.0, nrmse: 0.24397924444397501 },
    QualityReference { lane: "regression", seed: 55, accuracy: 0.0, brier: 0.0, nrmse: 0.24407533069232981 },
];
